spring.application.name=agent-platform
spring.graphql.graphiql.enabled=true


spring.ai.openai.api-key=${GROQ_API_KEY} 
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=${GROQ_MODEL}
spring.ai.openai.chat.options.extra-body.reasoning_format=hidden

# OpenTelemetry
management.tracing.sampling.probability=1.0

management.opentelemetry.tracing.export.otlp.endpoint=${LANGFUSE_BASE_URL}/api/public/otel/v1/traces
management.opentelemetry.tracing.export.otlp.headers.Authorization=${LANGFUSE_OTEL_AUTH}
management.opentelemetry.tracing.export.otlp.headers.x-langfuse-ingestion-version=4
management.otlp.metrics.export.enabled=false


# Kafka
# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

spring.kafka.consumer.group-id=agent-platform-execution-worker
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.puneet.agentplatform.execution