spring.application.name=agent-platform
spring.graphql.graphiql.enabled=true


spring.ai.openai.api-key=${GROQ_API_KEY} 
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=${GROQ_MODEL}
spring.ai.openai.chat.options.extra-body.reasoning_format=hidden

# OpenTelemetry
management.tracing.sampling.probability=1.0

management.opentelemetry.tracing.export.otlp.endpoint=${LANGFUSE_BASE_URL}/api/public/otel/v1/traces
management.opentelemetry.tracing.export.otlp.headers.Authorization=${LANGFUSE_OTEL_AUTH}
management.opentelemetry.tracing.export.otlp.headers.x-langfuse-ingestion-version=4
management.otlp.metrics.export.enabled=false
