spring.application.name=agent-platform
spring.graphql.graphiql.enabled=true


spring.ai.openai.api-key=${GROQ_API_KEY} 
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=${GROQ_MODEL}
spring.ai.openai.chat.options.extra-body.reasoning_format=hidden
